version: "3.7"

services:
  testdatagenerator:
    image: docker.miracum.org/fhir/fhir-generator:v1.2.0
    volumes:
      - ./config:/opt/testdata-generator/src/config
      - ./input:/opt/testdata-generator/input
      - ./output:/opt/testdata-generator/output
      - ./largerFhirBundles:/opt/testdata-generator/largerFhirBundles
    networks:
      - fhir-benchmark
    entrypoint: sh -c "tail -f /dev/null"

networks:
  fhir-benchmark:
    external: true
    name: fhir-benchmark
